In [1]:
#import dependencies
import pandas as pd
import sqlite3

#show all columns in dfs
pd.set_option("display.max_columns", None)

In [2]:
#connect to SQLite db
conn = sqlite3.connect('pokedex.db')

In [3]:
#read in the csv
pokedex = pd.read_csv('Pokedex_Ver8.csv')
pokedex.head()

,NUMBER,CODE,SERIAL,NAME,TYPE1,TYPE2,COLOR,ABILITY1,ABILITY2,ABILITY HIDDEN,GENERATION,LEGENDARY_FLAG,MEGA_EVOLUTION_FLAG,HEIGHT,WEIGHT,HP,ATK,DEF,SP_ATK,SP_DEF,SPD,TOTAL,CAPTURE_RATE,BASE_EGG_HATCH_CYCLE,BASE_EGG_HATCH_STEPS,EGG_GROUP1,EGG_GROUP2,BASE_EXP,EFFORT_HP,EFFORT_ATK,EFFORT_DEF,EFFORT_SP_ATK,EFFORT_SP_DEF,EFFORT_SPD,EFFORT_TOTAL
0,1,1,11,Bulbasaur,Grass,Poison,Green,Overgrow,NaN,Chrolophyll,1,0,0,0.7,6.9,45,49,49,65,65,45,318,45,20,5120,Monster,Grass,64,0,0,0,1,0,0,1
1,2,1,21,Ivysaur,Grass,Poison,Green,Overgrow,NaN,Chrolophyll,1,0,0,1.0,13.0,60,62,63,80,80,60,405,45,20,5120,Monster,Grass,142,0,0,0,1,1,0,2
2,3,1,31,Venusaur,Grass,Poison,Green,Overgrow,NaN,Chrolophyll,1,0,0,2.0,100.0,80,82,83,100,100,80,525,45,20,5120,Monster,Grass,263,0,0,0,2,1,0,3
3,3,2,32,Mega Venusaur,Grass,Poison,Green,Thick Fat,NaN,NaN,1,0,1,2.4,155.5,80,100,123,122,120,80,625,45,20,5120,Monster,Grass,313,0,0,0,2,1,0,3
4,4,1,41,Charmander,Fire,NaN,Red,Blaze,NaN,Solar Power,1,0,0,0.6,8.5,39,52,43,60,50,65,309,45,20,5120,Monster,Dragon,62,0,0,0,0,0,1,1

In [4]:
#clean the dataframe
pokedex.drop(pokedex.columns[23:35], axis=1, inplace=True)
pokedex.drop(columns='MEGA_EVOLUTION_FLAG', inplace=True)
pokedex[['TYPE2', 'ABILITY2', 'ABILITY HIDDEN']] = pokedex[['TYPE2', 'ABILITY2', 'ABILITY HIDDEN']].fillna('None')
pokedex.rename(columns={'ABILITY HIDDEN': 'ABILITY_HIDDEN'}, inplace=True)

pokedex.head()

,NUMBER,CODE,SERIAL,NAME,TYPE1,TYPE2,COLOR,ABILITY1,ABILITY2,ABILITY_HIDDEN,GENERATION,LEGENDARY_FLAG,HEIGHT,WEIGHT,HP,ATK,DEF,SP_ATK,SP_DEF,SPD,TOTAL,CAPTURE_RATE
0,1,1,11,Bulbasaur,Grass,Poison,Green,Overgrow,None,Chrolophyll,1,0,0.7,6.9,45,49,49,65,65,45,318,45
1,2,1,21,Ivysaur,Grass,Poison,Green,Overgrow,None,Chrolophyll,1,0,1.0,13.0,60,62,63,80,80,60,405,45
2,3,1,31,Venusaur,Grass,Poison,Green,Overgrow,None,Chrolophyll,1,0,2.0,100.0,80,82,83,100,100,80,525,45
3,3,2,32,Mega Venusaur,Grass,Poison,Green,Thick Fat,None,None,1,0,2.4,155.5,80,100,123,122,120,80,625,45
4,4,1,41,Charmander,Fire,None,Red,Blaze,None,Solar Power,1,0,0.6,8.5,39,52,43,60,50,65,309,45

In [5]:
#split dataframe into 8 different dataframes by the generation a pokemon first appeared
pokedex_gens = pokedex.groupby('GENERATION')
gen_1 = pokedex_gens.get_group(1)
gen_2 = pokedex_gens.get_group(2)
gen_3 = pokedex_gens.get_group(3)
gen_4 = pokedex_gens.get_group(4)
gen_5 = pokedex_gens.get_group(5)
gen_6 = pokedex_gens.get_group(6)
gen_7 = pokedex_gens.get_group(7)
gen_8 = pokedex_gens.get_group(8)

In [6]:
#combine gens 1 - 6 to create one larger dataframe
gens_1_to_6 = gen_1.append(gen_2).append(gen_3).append(gen_4).append(gen_5).append(gen_6)
gens_1_to_6.head()

,NUMBER,CODE,SERIAL,NAME,TYPE1,TYPE2,COLOR,ABILITY1,ABILITY2,ABILITY_HIDDEN,GENERATION,LEGENDARY_FLAG,HEIGHT,WEIGHT,HP,ATK,DEF,SP_ATK,SP_DEF,SPD,TOTAL,CAPTURE_RATE
0,1,1,11,Bulbasaur,Grass,Poison,Green,Overgrow,None,Chrolophyll,1,0,0.7,6.9,45,49,49,65,65,45,318,45
1,2,1,21,Ivysaur,Grass,Poison,Green,Overgrow,None,Chrolophyll,1,0,1.0,13.0,60,62,63,80,80,60,405,45
2,3,1,31,Venusaur,Grass,Poison,Green,Overgrow,None,Chrolophyll,1,0,2.0,100.0,80,82,83,100,100,80,525,45
3,3,2,32,Mega Venusaur,Grass,Poison,Green,Thick Fat,None,None,1,0,2.4,155.5,80,100,123,122,120,80,625,45
4,4,1,41,Charmander,Fire,None,Red,Blaze,None,Solar Power,1,0,0.6,8.5,39,52,43,60,50,65,309,45

In [7]:
#save the dataframes as SQL tables in the database
gens_1_to_6.to_sql('gens_1_to_6', conn, index=False)
gen_7.to_sql('gen_7', conn, index=False)
gen_8.to_sql('gen_8', conn, index=False)

In [8]:
#close the db connection
conn.close()